export default {
  id: 'acs',
  subhead: 'Build ACS reference entries and numbered in-text citations for chemistry papers and lab reports, free.',
  intro: '<p>ACS style comes from the American Chemical Society and is documented in The ACS Guide to Scholarly Communication. It is the standard for chemistry and closely related fields such as biochemistry, materials science, and chemical engineering, and it is what most ACS journals expect from authors. The style is built around the way chemists write: heavy on primary literature, with frequent references to journal articles and a strong emphasis on precise source detail. A distinctive feature is that ACS allows more than one way to mark citations in the text, including numbers and an author-date approach, while still pointing to a single ordered reference list. Journal titles are abbreviated using established chemistry conventions. The result is a compact citation system that suits research papers, theses, and lab reports where the chemical literature is dense and the source trail needs to stay easy to follow.</p>',
  formatOverview: '<h2>ACS format overview</h2><p>ACS supports a few in-text citation methods. The most common are numeric: a number marks each source where you cite it, often as a superscript or in parentheses, and the numbers tie to entries in the reference list. The reference list is usually ordered by the sequence in which sources appear, so numbering follows your text. ACS also permits an author-name approach in some contexts. Each reference entry carries authors, title, journal or book, year, and locating details, with journal names given in abbreviated form. Pick a single method and keep it consistent across the whole document. Use the generator above to produce both the in-text marker and the matching reference entry, then check element names, formulas, and titles, which depend on what you type in.</p>',
  faq: [
    { q: 'Does ACS use numbers or author names for citations?', a: 'ACS allows more than one method, including numeric markers and an author-date style. Pick one approach and use it consistently throughout your document.' },
    { q: 'Which journals require ACS style?', a: 'Most journals published by the American Chemical Society expect ACS style, and it is common across chemistry, biochemistry, and materials science coursework.' },
    { q: 'Are journal titles abbreviated in ACS references?', a: 'Yes. ACS uses standard abbreviated chemistry journal titles. The generator applies the abbreviated form for journal article sources.' },
    { q: 'How is the ACS reference list ordered?', a: 'In the common numeric method, references are listed in the order sources first appear in your text rather than alphabetically.' },
    { q: 'Can I cite a dataset or website in ACS style?', a: 'Yes. Select the source type in the tool and the form adjusts to the right fields. ACS handles websites, datasets, books, and journal articles, each with its own format.' },
  ],
};
