export default {
  id: 'ama',
  subhead: 'Generate AMA reference list entries and superscript in-text numbers for medical and health science papers, free.',
  intro: '<p>AMA style is the citation system of the American Medical Association, set out in the AMA Manual of Style and used across medicine, nursing, pharmacy, public health, and the wider biomedical literature. It is the default for many clinical journals, medical school assignments, and research submissions. What sets AMA apart is its reliance on numbers rather than author names in the running text: each source is assigned a number the first time it appears, and that number follows the source through the rest of the paper. Journal titles are abbreviated to standard forms, and author lists are handled compactly. The style is built for dense, evidence-heavy writing where many sources are cited in quick succession, so it keeps the body text clean while pushing full source detail into a numbered reference list at the end.</p>',
  formatOverview: '<h2>AMA format overview</h2><p>AMA uses a citation-sequence system. In the body of your paper, sources are marked with a small superscript number placed where you refer to them, and the numbers run in the order sources first appear. Reuse the same number every time you cite that source again. The reference list at the end is ordered by those numbers, not alphabetically, so reference one is the first source you cited. Each numbered entry carries the full details: authors, article or chapter title, journal or book, year, and locating information such as volume and pages. Journal names are given in their abbreviated form. Use the generator above to build both the superscript marker and the matching numbered entry, then confirm names and titles against your source.</p>',
  faq: [
    { q: 'Why does AMA use superscript numbers instead of author names?', a: 'AMA is a numbered, citation-sequence style designed for medical writing that cites many sources quickly. Numbers keep the running text uncluttered while the full details live in the reference list.' },
    { q: 'Do AMA references go in alphabetical order?', a: 'No. The reference list is ordered by the sequence in which sources first appear in your text, so the first source you cite is reference number one.' },
    { q: 'Are journal names abbreviated in AMA style?', a: 'Yes. AMA uses standard abbreviated journal titles rather than full names. The generator applies the abbreviated form when you select a journal article.' },
    { q: 'What if I cite the same source more than once?', a: 'Reuse the original number every time. A source keeps the same reference number throughout the paper no matter how often you cite it.' },
    { q: 'Is AMA the right style for a medical or nursing assignment?', a: 'Often yes, since AMA is standard across medicine, nursing, pharmacy, and public health. Check your instructor or target journal, as some health programs use APA instead.' },
  ],
};
