export default {
  id: 'apa',
  subhead: 'APA 7th edition is one of the most widely used citation styles, standard across psychology, education, and the social sciences.',
  intro: '<p>APA style comes from the American Psychological Association, and the current 7th edition is one of the most widely used citation styles in the world. It is the standard across psychology, education, nursing, and the social sciences, and many other fields adopt it too, so most students meet it at some point. APA is an author-date style: you credit a source in the text with the author and the year, then give full details in an alphabetical reference list at the end. The design reflects research where the recency of a study matters, so the year sits right beside the author in every citation. APA 7 also added clearer rules for online sources and digital identifiers, which is part of why it is so popular for modern research. This generator formats APA 7th edition references and in-text citations so the authors, year, titles, and source details follow the published order, punctuation, and capitalization exactly, leaving you to focus on the writing.</p>',
  formatOverview: '<h2>APA format overview</h2><p>APA uses two linked parts. In the body of your paper you place a short in-text citation with the author surname and the publication year, adding a page number when you quote directly. At the end you provide a reference list that gives every source in full, arranged alphabetically by author surname and formatted with a hanging indent. The author and year in the text match the start of the matching reference entry, which is how a reader moves from your sentence to the full source. APA 7 sets clear conventions for the author, date, title, and source elements that make up each entry. The generator above builds the in-text citation and the reference entry together so they stay consistent. Check the worked examples below for the exact APA 7th edition layout of your source type, whether a book, journal article, or website.</p>',
  faq: [
    { q: 'Which edition of APA does this generator use?', a: 'It follows APA 7th edition, the current version published by the American Psychological Association, which updated the rules for online sources and several formatting details from the 6th edition.' },
    { q: 'Who uses APA style?', a: 'APA is one of the most widely used styles and is standard in psychology, education, nursing, and the social sciences, with many other disciplines adopting it as well.' },
    { q: 'How do I write an APA in-text citation?', a: 'Give the author surname and the year, for example in parentheses at the end of a sentence, and add a page number when you quote directly. The generator shows the in-text form next to the reference.' },
    { q: 'What changed in APA 7th edition?', a: 'APA 7 simplified several rules, updated how online sources and DOIs are handled, and adjusted formatting details. This generator follows the 7th edition throughout.' },
    { q: 'How do I cite a website in APA 7?', a: 'Provide the author or organization, the date, the page title, and the site details. Select the website source type in the tool and the form will prompt for the fields APA 7 needs.' },
  ],
};
