export default {
  id: 'apsa',
  subhead: 'Create APSA author-date references and in-text citations for political science papers, free.',
  intro: '<p>APSA style comes from the American Political Science Association and is the standard for political science writing, including journal articles, conference papers, and coursework in the field. It is documented in the APSA style manual and is closely related to the Chicago author-date tradition, which it adapts for the conventions of political science. The style suits a discipline that draws on a broad mix of sources, from peer-reviewed research and books to government documents, public datasets, polling, and policy reports, and it is built to handle that range cleanly. Its defining feature is the author-date citation: sources are pointed to in the text by author and year, with the full detail collected in an alphabetical reference list. This keeps the running argument readable while letting readers trace empirical claims, an important fit for a field where evidence often comes from data and official records.</p>',
  formatOverview: '<h2>APSA format overview</h2><p>APSA uses an author-date system. In the text you cite a source with the author and year in parentheses at the point you use it, adding a page number when you quote or refer to a specific passage. Those in-text pointers match a reference list at the end, arranged alphabetically by author. Each reference entry carries the authors, year, title, and the publication or source details, including publisher, journal, or the issuing body for a government or data source. Multiple works by the same author are ordered by year. Use the generator above to produce both the in-text citation and the matching reference entry, then proofread author names, agency names, and titles, which depend on the details you enter, since political science sources often include institutions as authors.</p>',
  faq: [
    { q: 'What citation system does APSA use?', a: 'APSA uses an author-date system, citing sources by author and year in the text with a matching alphabetical reference list at the end.' },
    { q: 'How is APSA related to Chicago style?', a: 'APSA is closely based on the Chicago author-date tradition, adapted for political science conventions and the kinds of sources the field relies on.' },
    { q: 'How do I cite a government document or dataset in APSA?', a: 'Select the source type in the tool and the form adjusts. APSA handles government reports, datasets, and official records, often treating the issuing body as the author.' },
    { q: 'Is the APSA reference list alphabetical?', a: 'Yes. Entries are arranged alphabetically by author, and multiple works by the same author are ordered by year.' },
    { q: 'When do I include a page number in an APSA citation?', a: 'Add a page number in the in-text citation when you quote directly or refer to a specific passage, so readers can locate the exact point.' },
  ],
};
