export default {
  id: 'asa',
  subhead: 'ASA is the author-date citation style of the American Sociological Association, used across sociology and related social sciences.',
  intro: '<p>ASA style is the citation system set out by the American Sociological Association in its official style guide. It is the standard for sociology and is also used in related social science fields where research draws on surveys, fieldwork, and theory. ASA is an author-date style, which means it identifies sources in the text by author and year rather than by footnote number, keeping the reader focused on who said what and when. That emphasis on the author and the date suits a discipline where the timing of a study and the scholar behind it matter to the argument. The style is concise and practical, with a references section that gathers full source details at the end of the paper. This generator formats ASA citations and reference entries so the names, dates, titles, and publication details fall into the order and punctuation the ASA guide requires.</p>',
  formatOverview: '<h2>ASA format overview</h2><p>ASA uses two connected parts. In the body of your paper you give a short parenthetical citation with the author surname and the year, adding a page number when you quote or point to a specific passage. At the end of the paper, a references section lists every source in full, arranged alphabetically by author surname. The in-text citation and the references entry share the same author and year, which is how readers move from the text to the full source. The generator above produces both the parenthetical citation and the matching references entry at once. Use the worked examples below to confirm the exact ASA format for the source type you are citing, whether it is a book, a journal article, or a website.</p>',
  faq: [
    { q: 'What field uses ASA style?', a: 'ASA is the citation style of the American Sociological Association and is used mainly in sociology, along with related social science courses and journals that follow the ASA guide.' },
    { q: 'Is ASA an author-date style?', a: 'Yes. ASA identifies sources in the text by author surname and year, then lists full details in a references section, rather than using numbered footnotes.' },
    { q: 'How is ASA different from APA?', a: 'Both are author-date social science styles, but they differ in punctuation, capitalization, and reference list details. Use ASA when your sociology course or journal specifies it, and do not mix the two.' },
    { q: 'When do I include a page number in an ASA citation?', a: 'Add a page number in the parenthetical citation when you quote directly or refer to a specific part of a source, so readers can locate the exact passage.' },
    { q: 'How do I cite a source with several authors in ASA?', a: 'Name the authors as the ASA guide directs for the number you have, and shorten longer author lists in the text. The generator arranges the names for you once you enter them.' },
  ],
};
