export default {
  id: 'asme',
  subhead: 'ASME is the numbered citation style of the American Society of Mechanical Engineers, used in mechanical engineering writing.',
  intro: '<p>ASME style is the citation system published by the American Society of Mechanical Engineers for its journals, conference papers, and technical publications. It is the standard for mechanical engineering and is used by students, researchers, and practitioners writing in that field. ASME is a numbered style, which means sources are cited in the text by a number rather than by author and year. The first source you cite gets number one, the next new source gets number two, and so on, with the numbers pointing to a numbered references list. This keeps the running text compact and uncluttered, which suits dense technical writing full of equations, figures, and data. The references list at the end gathers the full details of each source in the order they first appear. This generator formats ASME references and the matching in-text numbers so the authors, titles, and publication details follow the order and punctuation the ASME guidelines require.</p>',
  formatOverview: '<h2>ASME format overview</h2><p>ASME uses a numbered system with two parts. In the body of your paper you cite a source with a number, typically shown in brackets, placed where you refer to the work. Each source keeps the same number every time you cite it, and new sources are numbered in the order they first appear in the text. At the end of the paper a references list presents every source in full, ordered by that citation number rather than alphabetically. The number in the text matches the entry with the same number in the list, which is how a reader follows a citation to its source. The generator above produces the numbered reference entry and shows the in-text number for it. Use the worked examples below to confirm the exact ASME format for the source type you are citing.</p>',
  faq: [
    { q: 'What field uses ASME style?', a: 'ASME style is used in mechanical engineering, following the guidelines of the American Society of Mechanical Engineers for its journals, conference papers, and technical reports.' },
    { q: 'Is ASME a numbered citation style?', a: 'Yes. ASME cites sources by number in the text rather than by author and year, and the references list is ordered by those citation numbers.' },
    { q: 'How are sources numbered in ASME?', a: 'Sources are numbered in the order they first appear in the text. The first cited source is one, the next new source is two, and each source keeps its number on later citations.' },
    { q: 'How is ASME different from IEEE?', a: 'Both are numbered engineering styles, but they come from different organizations and differ in punctuation and reference details. Use ASME for mechanical engineering work that calls for it, and follow the ASME guidelines closely.' },
    { q: 'How is the ASME references list ordered?', a: 'It is ordered by citation number, meaning the sequence sources first appear in your text, not alphabetically by author. The generator keeps each entry tied to its number.' },
  ],
};
