export default {
  id: 'bluebook',
  subhead: 'Generate Bluebook legal citations and references for law review articles and legal documents, free.',
  intro: '<p>The Bluebook is the standard system of legal citation in the United States, used in law schools, law reviews, court documents, and legal scholarship. It is the format law students learn early and that practitioners and editors rely on for citing cases, statutes, regulations, and secondary legal sources. Bluebook citation is distinct from academic styles because legal writing cites a particular kind of authority: court decisions, codified statutes, and official reports, each with its own conventions for naming, abbreviating, and locating the source. It is built to point readers precisely to the controlling text, often down to a specific page or section. The system distinguishes between citations in scholarly footnotes and those in practitioner documents, and it leans heavily on abbreviations for courts, reporters, and publications. If you are writing a law review note, a brief, or a memo, Bluebook is almost certainly the expected format.</p>',
  formatOverview: '<h2>Bluebook format overview</h2><p>Bluebook citations are typically placed in footnotes in scholarly writing or inline in practitioner documents, rather than in an author-date pointer. A citation identifies the authority, such as a case, statute, or article, with the locating detail a reader needs to find it, often including a reporter, code, or volume and the relevant page or section. The style uses standardized abbreviations for courts, reporters, and journals, and it treats different source types with their own rules. There is no single alphabetical reference list in the academic sense; instead each citation stands on its own where it is used. Use the generator above to assemble a citation for your source type, then check party names, dates, and locating numbers carefully, since legal citations depend on exact detail that you supply.</p>',
  faq: [
    { q: 'What is the Bluebook used for?', a: 'It is the standard system of legal citation in the United States, used in law schools, law reviews, court filings, and legal scholarship to cite cases, statutes, and other authorities.' },
    { q: 'Does Bluebook use a reference list like academic styles?', a: 'Not in the usual sense. Legal citations typically appear in footnotes or inline at the point of use rather than collected in a single alphabetical list.' },
    { q: 'How does Bluebook cite a court case?', a: 'A case citation identifies the parties and gives the locating detail a reader needs, such as the reporter and the relevant page, along with the court and year where required.' },
    { q: 'Why are there so many abbreviations in Bluebook?', a: 'Bluebook uses standardized abbreviations for courts, reporters, and journals to keep dense legal citations compact while still pointing precisely to the source.' },
    { q: 'Is Bluebook citation different for student papers and practice documents?', a: 'Yes. The Bluebook distinguishes citation conventions for scholarly footnotes from those used in practitioner documents like briefs and memos.' },
  ],
};
