export default {
  id: 'chicago',
  subhead: 'Chicago is the style of The Chicago Manual of Style, offering two systems: author-date and notes-bibliography with footnotes.',
  intro: '<p>Chicago style comes from The Chicago Manual of Style, one of the oldest and most detailed style guides in American publishing. It is widely used in history, the humanities, and the publishing industry, and it is known for being flexible enough to cover almost any kind of source. What makes Chicago distinctive is that it offers two separate systems rather than one. The notes-bibliography system uses numbered footnotes or endnotes paired with a bibliography, and is favored in history and the arts. The author-date system uses brief parenthetical citations tied to a reference list, and suits the sciences and social sciences. Writers choose the system that fits their field or their instructor. This generator formats Chicago references and citations so the order, punctuation, and capitalization follow the published rules for the system you select.</p>',
  formatOverview: '<h2>Chicago format overview</h2><p>How a Chicago citation looks depends on which system you use. In the notes-bibliography system, you place a superscript number in the text and give the full source details in a matching footnote or endnote, then list every source again in a bibliography at the end. In the author-date system, you put a short parenthetical citation in the text containing the author and year, and readers find the full details in a reference list. In both systems the end-of-paper list collects all sources in alphabetical order by author. The generator above builds the in-text element and the matching list entry together, so you can copy both and check them against the worked examples below for your source type.</p>',
  faq: [
    { q: 'What is the difference between the two Chicago systems?', a: 'Notes-bibliography uses footnotes or endnotes plus a bibliography and is common in history and the humanities. Author-date uses short parenthetical citations plus a reference list and is common in the sciences and social sciences.' },
    { q: 'Which Chicago system should I use?', a: 'Follow your instructor or publisher first. If you have no guidance, pick notes-bibliography for history and arts writing and author-date for science and social science writing.' },
    { q: 'Is Chicago style the same as Turabian?', a: 'They are closely related. Turabian is a student-focused adaptation of Chicago by Kate Turabian, so the core rules match, with Turabian aimed at term papers, theses, and dissertations.' },
    { q: 'Does Chicago use footnotes or endnotes?', a: 'The notes-bibliography system supports both. Footnotes sit at the bottom of the page and endnotes collect at the end of the document or chapter; your instructor or publisher decides which to use.' },
    { q: 'How do I cite a source with no author in Chicago?', a: 'Begin the entry with the title instead of an author, and use a shortened form of the title in the in-text citation or note. The generator adjusts the format when you leave the author field empty.' },
  ],
};
