export default {
  id: 'cse',
  subhead: 'Generate CSE references and in-text citations for biology and life science writing, free.',
  intro: '<p>CSE style is maintained by the Council of Science Editors and is widely used across the life sciences, including biology, ecology, genetics, and many natural science programs. It grew out of the long tradition of scientific publishing and is a common requirement for biology coursework and research papers. What makes CSE notable is its flexibility: it supports more than one citation system, so the same source can be marked by author and year or by a sequence number depending on which approach your course or journal follows. This lets writers match the convention of their subfield rather than forcing a single format. CSE puts a premium on precise, traceable source detail, which fits a discipline built on experimental evidence and the primary literature. Whichever system you use, the goal is the same: a clear, consistent trail from a claim in your text to the full source.</p>',
  formatOverview: '<h2>CSE format overview</h2><p>CSE offers more than one citation system, and the two most common are name-year and citation-sequence. In the name-year system you cite the author and year in the text, and the reference list is alphabetical by author. In citation-sequence you mark sources with numbers in the order they appear, and the reference list follows that numeric order. A related citation-name variant numbers an alphabetized list. Pick one system and stay with it across the whole paper. Each reference entry carries authors, title, the journal or book, year, and locating details. Use the generator above to build both the in-text citation and the matching reference entry in the CSE system shown, then verify species names, author names, and titles, which depend on what you enter.</p>',
  faq: [
    { q: 'Which CSE citation system should I use?', a: 'CSE supports name-year and citation-sequence systems, among others. Use whichever your instructor or target journal specifies, and keep it consistent throughout the paper.' },
    { q: 'Is CSE the same as the old CBE style?', a: 'CSE is the successor to the Council of Biology Editors (CBE) style. The council broadened its scope and renamed the manual, so newer guidance uses CSE.' },
    { q: 'Is the CSE reference list alphabetical or numbered?', a: 'It depends on the system. Name-year lists references alphabetically by author, while citation-sequence lists them in the order they first appear in the text.' },
    { q: 'Who uses CSE style?', a: 'It is common in biology and the life sciences, including ecology, genetics, and natural science programs, and is used by a number of science journals.' },
    { q: 'How do I cite a source in the text with CSE name-year?', a: 'Give the author and year at the point you use the source, and keep the full entry in an alphabetical reference list. The generator shows the matching in-text form.' },
  ],
};
