export default {
  id: 'harvard',
  subhead: 'Harvard is a widely used author-date referencing style, especially common in universities across the UK and Australia.',
  intro: '<p>Harvard referencing is an author-date system used across many subjects, and it is especially common in universities in the UK and Australia. Rather than a single rulebook from one organization, Harvard is a family of closely related author-date styles, which is why different institutions publish their own Harvard guides with small variations. The shared idea is simple and consistent: you credit a source in the text with the author and the year, and give the full details in an alphabetical reference list at the end. That clarity is why Harvard is taught so widely as a first referencing style. Because local versions differ in fine detail, the best practice is to follow your university or department guide where one exists. This generator formats Harvard references and in-text citations into a clean, widely accepted author-date pattern so your names, dates, titles, and source details are ordered and punctuated consistently throughout your work.</p>',
  formatOverview: '<h2>Harvard format overview</h2><p>Harvard works through two linked parts. In the body of your writing you place a short in-text citation with the author surname and the year in brackets, adding a page number when you quote directly. At the end of your work you provide a reference list that gives the full details of every source, arranged alphabetically by author surname. The author and year in the text match the start of the matching reference entry, which is how a reader moves from your sentence to the source. The generator above builds the in-text citation and the reference list entry together so they stay consistent. Check the worked examples below for the exact Harvard layout of your source type, and follow your own institution guide if it sets specific local rules.</p>',
  faq: [
    { q: 'Is there one official Harvard style?', a: 'No. Harvard is a family of author-date styles rather than a single published standard, so universities often issue their own Harvard guides with minor differences. Follow your institution guide when one is provided.' },
    { q: 'Where is Harvard referencing used most?', a: 'Harvard is widely used in universities across the UK and Australia, and in many other countries, across a broad range of subjects from business to the social sciences.' },
    { q: 'How is Harvard different from APA?', a: 'Both are author-date styles and look similar in the text. They differ in punctuation and reference list formatting, and APA is a single published standard while Harvard varies by institution.' },
    { q: 'Do I need a page number in a Harvard in-text citation?', a: 'Include a page number when you quote directly or point to a specific passage, so the reader can find it. For a general reference to a whole work, the author and year are usually enough.' },
    { q: 'How do I cite a website in Harvard referencing?', a: 'Give the author or organization, the year, the page title, and the access details as your guide requires. Select the website source type in the tool and the form will prompt for these fields.' },
  ],
};
