export default {
  id: 'ieee',
  subhead: 'Create IEEE reference entries and bracketed in-text numbers for engineering and computer science papers, free.',
  intro: '<p>IEEE style is the citation system of the Institute of Electrical and Electronics Engineers, and it is the dominant format across engineering, computer science, electronics, and telecommunications. If you are writing for an IEEE conference or journal, or completing an engineering or CS assignment, this is almost always the expected style. Its signature feature is the bracketed number: sources are cited in the text with a number in square brackets, like a marker you can read at a glance, rather than with author names. Those numbers tie directly to a numbered reference list. The style is well suited to technical writing that leans on standards, conference proceedings, patents, datasheets, and journal papers, and it keeps the running text terse so equations and figures stay readable. It is one of the most widely recognized numbered citation systems in the technical world.</p>',
  formatOverview: '<h2>IEEE format overview</h2><p>IEEE uses a citation-sequence system with bracketed numbers. In the text you place a number in square brackets where you refer to a source, and you can cite the bracket on its own or fold it into a sentence. The numbers are assigned in the order sources first appear, and you reuse a source number every time you cite it again. The reference list is ordered by those numbers, so the first source cited is reference one. Each entry lists authors, title, the publication, conference, or standard, and locating details such as volume, pages, and year. Use the generator above to produce both the bracketed marker and the numbered reference entry, then proofread author initials and technical titles, which depend on the details you enter.</p>',
  faq: [
    { q: 'Why does IEEE use bracketed numbers like [1]?', a: 'IEEE is a numbered citation style. The square-bracket number is a compact pointer to the reference list, which keeps technical text and equations easy to read.' },
    { q: 'Is the IEEE reference list alphabetical?', a: 'No. References are numbered and listed in the order sources first appear in your text, so reference one is the first source you cited.' },
    { q: 'Can I cite a standard, patent, or datasheet in IEEE?', a: 'Yes. Select the source type in the tool and the form adjusts. IEEE is built for technical sources including standards, conference papers, and patents.' },
    { q: 'How do I cite the same source twice in IEEE?', a: 'Reuse its original bracketed number. A source keeps the same number throughout the document however many times you reference it.' },
    { q: 'Where does the bracketed number go in a sentence?', a: 'Place it at the point where you refer to the source. You can use the bracket alone or include it as part of the sentence, such as referring to a method in a numbered source.' },
  ],
};
