export default {
  id: 'mla',
  subhead: 'MLA 9th edition is one of the most widely used citation styles, standard across literature, languages, and the humanities.',
  intro: '<p>MLA style comes from the Modern Language Association, and the current 9th edition is one of the most widely used citation styles, especially in literature, languages, and the wider humanities. Many students first learn it in English classes, where close reading of texts is central. What makes MLA distinctive is its in-text approach: you point to a source with the author and a page number rather than a year, which suits writing that quotes and analyzes specific passages closely. MLA 9 is built around a flexible template of core elements, so a single set of principles can describe almost any source, from a novel to a web page to a video, without a separate rule for every format. Full details live in a Works Cited list at the end of the paper. This generator formats MLA 9th edition citations and Works Cited entries so the author, title, and source details follow the published order, punctuation, and capitalization.</p>',
  formatOverview: '<h2>MLA format overview</h2><p>MLA uses two linked parts. In the body of your paper you give a short in-text citation, usually the author surname and a page number, so a reader can find the exact passage. At the end you provide a Works Cited list with the full details of every source, arranged alphabetically by author surname and set with a hanging indent. The author name that opens each Works Cited entry matches the name in your in-text citation, which is how a reader moves from your sentence to the source. MLA 9 organizes each entry around a set of core elements, which keeps the format consistent across very different source types. The generator above builds the in-text citation and the Works Cited entry together. Check the worked examples below for the exact MLA 9th edition layout of your source type.</p>',
  faq: [
    { q: 'Which edition of MLA does this generator use?', a: 'It follows MLA 9th edition, the current version from the Modern Language Association, which builds on the core-elements approach introduced in the 8th edition.' },
    { q: 'Who uses MLA style?', a: 'MLA is one of the most widely used styles and is standard in literature, languages, and the humanities, where it is often the first citation style students learn.' },
    { q: 'Why does MLA use author and page instead of a year?', a: 'MLA in-text citations point to the author and a page number so readers can find the exact passage you quote or analyze, which suits close reading of texts.' },
    { q: 'What is the MLA core elements approach?', a: 'MLA 9 describes each source using a shared set of core elements rather than a separate rule for every format, so the same principles cover books, web pages, videos, and more.' },
    { q: 'What is a Works Cited list?', a: 'It is the MLA reference list at the end of your paper, giving full details of every source you cited, arranged alphabetically by author surname.' },
  ],
};
