export default {
  id: 'turabian',
  subhead: 'Build Turabian references and in-text citations for student papers in history and the humanities, free.',
  intro: '<p>Turabian style is the student-focused version of the Chicago Manual of Style, named for Kate Turabian, who wrote the classic manual for term papers, theses, and dissertations. It is widely used in history and the humanities, and it is a common requirement for college and graduate writing where instructors want Chicago conventions presented in a form aimed at students rather than professional publishers. Like Chicago, Turabian offers two citation approaches, so writers can match either a notes-based tradition common in history or an author-date tradition common in some social and natural sciences. This generator builds the author-date form. The style is valued for handling a wide range of sources, from archival material to books and journal articles, with the careful detail that humanities research depends on. If your assignment asks for Turabian, you are essentially following Chicago in a student-friendly shape.</p>',
  formatOverview: '<h2>Turabian format overview</h2><p>Turabian provides two systems. The notes-bibliography system uses numbered notes for citations plus a bibliography, and is favored in history and the humanities. The author-date system, which this generator produces, cites the author and year in parentheses in the text and pairs them with an alphabetical reference list. In author-date, the in-text citation is a short pointer with the author and year, and the full source detail, including authors, title, publisher or journal, and year, lives in the reference list. Pick the system your assignment requires and use it throughout. Use the generator above to create both the in-text citation and the matching reference entry, then proofread names, titles, and publication details against your source, since those depend on the information you enter.</p>',
  faq: [
    { q: 'How is Turabian different from Chicago style?', a: 'Turabian is the student edition of Chicago. It follows the same conventions but is written for term papers, theses, and dissertations rather than professional publishing.' },
    { q: 'Does Turabian use footnotes or author-date citations?', a: 'It offers both: a notes-bibliography system common in history and an author-date system. This generator produces the author-date form.' },
    { q: 'Who typically uses Turabian style?', a: 'It is common in history and the humanities and is a frequent requirement for college and graduate student papers across many disciplines.' },
    { q: 'Is the Turabian reference list alphabetical?', a: 'In the author-date system the reference list is alphabetical by author. The notes-bibliography system also keeps an alphabetical bibliography.' },
    { q: 'Can I cite archival or primary sources in Turabian?', a: 'Yes. Turabian, like Chicago, is built to handle a wide range of sources. Select the source type in the tool and the form adjusts to the right fields.' },
  ],
};
