export default [
  {
    styleId: 'apsa',
    sourceId: 'journal-article',
    answer: 'APSA uses an author-date system based on Chicago. Cite a journal article in the text with author last name and year, and give a reference list entry with author, year, article title, journal in italics, volume, issue, and page range, adding the DOI as a stable link.',
    steps: [
      { name: 'Author and year', text: 'Invert the first author name and place the year right after the author in the reference list, since APSA is author-date.' },
      { name: 'Article title', text: 'Give the article title in quotation marks, capitalized headline style.' },
      { name: 'Journal and volume', text: 'Italicize the journal name and add the volume and issue numbers.' },
      { name: 'Page range', text: 'Provide the full page range of the article in the reference list.' },
      { name: 'DOI', text: 'Close with the DOI as a full link, which APSA prefers over a database URL.' },
    ],
    formatNote: 'APSA orders a journal article as author, year, title, journal, volume, issue, and pages, following Chicago author-date. The worked example shows the reference entry and the matching in-text citation.',
    variations: [
      { q: 'How do I write the in-text citation for an article in APSA?', a: 'Give the author last name and year in parentheses, adding a page after a comma for a direct quote, for example (Smith 2024, 48).' },
      { q: 'How do I cite an article with three or more authors in APSA?', a: 'List all authors in the reference list, and in the text use the first author followed by et al. once the author count passes the APSA threshold.' },
      { q: 'How do I cite a journal article with no DOI in APSA?', a: 'Give a stable URL or the database name in place of the DOI, or end at the page range for a print article with neither.' },
      { q: 'How do I order multiple works by the same author in APSA?', a: 'List them by year in the reference list, and use a, b, c suffixes on the year when the same author has more than one work in the same year.' },
    ],
    faq: [
      { q: 'Is APSA an author-date or footnote style?', a: 'APSA is author-date, built on Chicago author-date, so citations appear in the text in parentheses rather than in footnotes.' },
      { q: 'Is the journal title italicized in APSA?', a: 'Yes. The journal name is italicized and the article title is placed in quotation marks.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'book',
    answer: 'In APSA cite a book in the text with author and year, and in the reference list give author, year, the title in italics, the place, and the publisher. APSA follows Chicago author-date conventions for political science writing.',
    steps: [
      { name: 'Author and year', text: 'Invert the author name and follow it with the year, since APSA places the date directly after the author.' },
      { name: 'Italicize the title', text: 'Set the full book title in italics, capitalized headline style.' },
      { name: 'Place and publisher', text: 'Give the place of publication and the publisher after the title.' },
      { name: 'Edition', text: 'Add the edition after the title when it is not the first.' },
      { name: 'In-text pinpoint', text: 'In the text, add a page after the year for a direct quotation.' },
    ],
    formatNote: 'APSA orders a book as author, year, title, place, and publisher, following Chicago author-date. The worked example shows both the reference entry and the in-text form.',
    variations: [
      { q: 'How do I cite an edited book or a chapter in APSA?', a: 'For a chapter, give the chapter author, year, chapter title, then In the edited book title, the editor, page range, place, and publisher.' },
      { q: 'How do I cite a book with a corporate author in APSA?', a: 'Use the organization as the author in both the text and the reference list, for example a government department or research institute.' },
      { q: 'How do I cite a reissued or later edition of a book in APSA?', a: 'Add the edition after the title and use the year of the edition you consulted as the date in the citation.' },
      { q: 'How do I cite a classic political theory text in APSA?', a: 'Cite the edition you used with its publication year, and you may note the original date if relevant to your argument.' },
    ],
    faq: [
      { q: 'Does APSA put the year next to the author for a book?', a: 'Yes. As an author-date style, APSA places the year immediately after the author in the reference list.' },
      { q: 'Is the publisher needed for a book in APSA?', a: 'Yes. APSA gives the place and publisher in the reference list, following Chicago author-date practice.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'website',
    answer: 'In APSA cite a web page with author or organization, year, the page title, the website name, and the URL, adding an access date when the page is undated. The in-text citation uses author and year.',
    steps: [
      { name: 'Author or owner', text: 'Use the page author, or the organization that owns the content when no individual is named.' },
      { name: 'Year', text: 'Give the publication or revision year right after the author, as APSA is author-date.' },
      { name: 'Title and site', text: 'Put the page title in quotation marks and give the website name separately.' },
      { name: 'URL', text: 'Paste the full URL to the exact page.' },
      { name: 'Access date', text: 'Add the date you accessed the page when no publication or revision date is shown.' },
    ],
    formatNote: 'APSA orders a web page as author, year, page title, site, and URL, following Chicago author-date. An access date covers an undated page, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a website with no author in APSA?', a: 'Use the organization that owns the site as the author. If no organization is identifiable, begin with the page title and keep author-date order in the text using a short title.' },
      { q: 'How do I cite a website with no date in APSA?', a: 'Use n.d. in place of the year in both the text and the reference list, and add the access date before the URL.' },
      { q: 'How do I cite a government or think tank web page in APSA?', a: 'Use the department or institute as the corporate author, give the year, the page title, the site, and the URL, which is common for political science sources.' },
      { q: 'How do I cite a dataset page on a website in APSA?', a: 'Name the producing organization, the year, the dataset title, and the URL, treating it as data so readers can locate and verify it.' },
    ],
    faq: [
      { q: 'Do I need an access date for a website in APSA?', a: 'An access date is needed mainly when the page is undated or likely to change; a clearly dated page may not require one.' },
      { q: 'Is the page title italicized for a website in APSA?', a: 'No. The page title goes in quotation marks and the website name stays in roman.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'youtube',
    answer: 'In APSA cite a YouTube video with the uploader, the year, the video title, YouTube, and the URL, following Chicago author-date for audiovisual sources. Note a timestamp in the text when you cite a specific moment.',
    steps: [
      { name: 'Uploader', text: 'Use the channel or account that posted the video as the author.' },
      { name: 'Year', text: 'Give the upload year right after the uploader, since APSA is author-date.' },
      { name: 'Title the video', text: 'Put the video title in quotation marks as shown on the watch page.' },
      { name: 'Platform and URL', text: 'Name YouTube and paste the full watch URL.' },
      { name: 'Timestamp', text: 'In the text, add the timestamp for the exact moment you reference.' },
    ],
    formatNote: 'APSA orders a YouTube video as uploader, year, title, YouTube, and URL, following Chicago author-date. A timestamp in the text pinpoints the moment, which the worked example shows.',
    variations: [
      { q: 'How do I cite a specific moment in a YouTube video in APSA?', a: 'Give the uploader and year in the text and add the timestamp, for example (TED 2010, at 4:35), since a video has no pages to pinpoint.' },
      { q: 'How do I cite a campaign or government YouTube video in APSA?', a: 'Use the campaign or agency channel as the author, the upload year, the title, YouTube, and the URL, which suits political science material.' },
      { q: 'How do I cite a YouTube video with no upload date in APSA?', a: 'Use n.d. for the year and add an access date, since streaming content can be edited or removed.' },
      { q: 'Is the uploader or speaker the author of a YouTube video in APSA?', a: 'The uploader is the author because they control the posted version, though you can name the speaker in your sentence for clarity.' },
    ],
    faq: [
      { q: 'Does APSA use author-date for YouTube videos?', a: 'Yes. The in-text citation gives the uploader and year, with a timestamp added for a precise moment.' },
      { q: 'Do I italicize a YouTube title in APSA?', a: 'No. The video title goes in quotation marks rather than italics.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'image',
    answer: 'In APSA cite an image with the creator, the year, a title or description, the medium, and the repository or website with URL, following Chicago author-date. The in-text citation uses the creator and year, or the title when no creator is named.',
    steps: [
      { name: 'Creator', text: 'Give the artist or photographer as the author; if unknown, begin with the title or a description.' },
      { name: 'Year', text: 'Provide the year the image was created or published, placed after the creator.' },
      { name: 'Title or describe', text: 'Use the formal title in italics, or a short description for an untitled work.' },
      { name: 'Medium and repository', text: 'Note the medium and name the archive, museum, or website holding the image.' },
      { name: 'URL', text: 'For an online image, give the full URL to the exact item.' },
    ],
    formatNote: 'APSA orders an image as creator, year, title or description, medium, and repository, following Chicago author-date. The worked example shows the online image form.',
    variations: [
      { q: 'How do I cite an image with no creator in APSA?', a: 'Begin with the title or a description and use it as the in-text anchor, then give the year, the repository, and the URL.' },
      { q: 'How do I cite a political map or infographic in APSA?', a: 'Name the producing organization as the creator, the year, the title, the source, and the URL, treating it as a graphic the reader can verify.' },
      { q: 'How do I cite a figure reproduced from another source in APSA?', a: 'Cite the source the figure came from and add a credit line under the figure, with the full entry in the reference list.' },
      { q: 'How do I cite a historical photograph from an archive in APSA?', a: 'Give the photographer if named or a description if not, the year, the holding archive, and the URL or collection identifier.' },
    ],
    faq: [
      { q: 'Does an image need a creator in APSA?', a: 'Not always. When no creator is named, you start with the title or a description and use that as the in-text anchor.' },
      { q: 'Are artwork titles italicized in APSA?', a: 'Yes. Formal artwork titles are italicized, while an untitled work uses a roman description.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'pdf',
    answer: 'In APSA cite a PDF by the underlying work, usually a report or government document, giving author or issuing body, year, the title in italics, the publisher, and the URL. APSA follows Chicago author-date, so a PDF is not a separate type.',
    steps: [
      { name: 'Identify the work', text: 'Decide whether the PDF is a report, book, or article, since that sets the APSA pattern rather than the file format.' },
      { name: 'Author or issuer', text: 'Use the named author or the organization that issued the document.' },
      { name: 'Year and title', text: 'Give the year after the author and italicize a standalone report title.' },
      { name: 'Publisher', text: 'Name the issuing body or publisher.' },
      { name: 'URL', text: 'Add the full URL to the PDF so the file can be retrieved.' },
    ],
    formatNote: 'APSA treats a PDF report as author, year, title, publisher, and URL, following Chicago author-date. The format label is optional, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a government report PDF in APSA?', a: 'Use the issuing agency as the author, give the year, the report title and any number, the publisher, and the URL to the file.' },
      { q: 'How do I cite a think tank working paper PDF in APSA?', a: 'Name the author or institute, the year, the paper title, the series and number, and the URL, which is common for political science research.' },
      { q: 'Do I write PDF in an APSA citation?', a: 'Usually no. APSA cites the underlying document and uses the URL, adding a format note only when it helps the reader find the file.' },
      { q: 'How do I cite a PDF with no clear author in APSA?', a: 'Use the issuing organization as the corporate author, or begin with the title when none is shown, keeping author-date order in the text.' },
    ],
    faq: [
      { q: 'Is a PDF a separate source type in APSA?', a: 'No. APSA cites the underlying report, book, or article and treats PDF only as the delivery format.' },
      { q: 'Is a report title italicized in APSA?', a: 'A standalone report title is italicized; a document that is part of a series uses quotation marks instead.' },
    ],
  },
  {
    styleId: 'apsa',
    sourceId: 'chatgpt',
    answer: 'APSA has no fixed AI rule, so cite ChatGPT by adapting its Chicago author-date base. Credit OpenAI, name ChatGPT and the version, give the date, and note that the conversation is not retrievable, often handling it in the text or a note rather than as a normal reference.',
    steps: [
      { name: 'Credit the owner', text: 'Use OpenAI as the author, since it makes and is responsible for ChatGPT.' },
      { name: 'Name the tool and version', text: 'Identify ChatGPT and the model version, because outputs differ across versions.' },
      { name: 'Describe the prompt', text: 'State in the text what you asked, since the prompt drives the generated response.' },
      { name: 'Date the response', text: 'Give the date you generated the output, as the same prompt can return different answers later.' },
      { name: 'Note non-retrievability', text: 'Add the tool URL and note that your specific session is not publicly retrievable.' },
    ],
    formatNote: 'APSA adapts its Chicago author-date base for ChatGPT, crediting OpenAI with the date and tool URL. Because the output is not retrievable, the worked example reflects a note style reference.',
    variations: [
      { q: 'How do I write the in-text citation for ChatGPT in APSA?', a: 'Give OpenAI and the year in parentheses, naming ChatGPT and the prompt in your sentence so the reader knows what produced the text.' },
      { q: 'Does ChatGPT go in the APSA reference list?', a: 'Because the conversation is not retrievable, many writers handle it in the text or a note; add a reference entry only if your instructor requires it.' },
      { q: 'How do I cite a specific ChatGPT model version in APSA?', a: 'Name the version alongside ChatGPT, since the model used shapes the output and lets readers understand which system answered.' },
      { q: 'Which date do I use for ChatGPT in APSA?', a: 'Use the date you generated the response, because AI output is not stable and the date fixes when it was produced.' },
    ],
    faq: [
      { q: 'Does APSA have an official AI citation rule?', a: 'Not yet. Writers adapt the Chicago author-date base, crediting OpenAI and treating the output as non-retrievable.' },
      { q: 'Who is the author of a ChatGPT response in APSA?', a: 'OpenAI is credited as the author, with ChatGPT and its version named as the tool that generated the text.' },
    ],
  },
];
