export default [
  {
    styleId: 'asa',
    sourceId: 'journal-article',
    answer: 'ASA uses an author-year system. Cite a journal article in the text with author last name and year, and in the reference list give author, year, the article title in quotation marks, the journal in italics, volume, issue, and the page range, adding the DOI at the end.',
    steps: [
      { name: 'Author and year', text: 'Invert the first author name and place the year right after it, since ASA is an author-year style.' },
      { name: 'Article title', text: 'Give the article title in quotation marks.' },
      { name: 'Journal and volume', text: 'Italicize the journal name and add the volume and issue.' },
      { name: 'Page range', text: 'Provide the full page range of the article in the reference list.' },
      { name: 'DOI', text: 'Close with the DOI so readers reach the exact article.' },
    ],
    formatNote: 'ASA orders a journal article as author, year, article title, journal, volume, issue, and pages. The worked example shows the reference entry and the matching in-text citation.',
    variations: [
      { q: 'How do I write the in-text citation for an article in ASA?', a: 'Give the author last name and year in parentheses, adding a page after a colon for a direct quote, for example (Smith 2024:48).' },
      { q: 'How do I cite an article with multiple authors in ASA?', a: 'List all authors in the reference list, inverting only the first name. In the text, use et al. once the author count passes the ASA threshold.' },
      { q: 'How do I cite a journal article with no DOI in ASA?', a: 'Give the URL or the database used in place of the DOI, or end at the page range for a print article that has neither.' },
      { q: 'How do I order several works by one author in ASA?', a: 'List them oldest first, and add a, b, c after the year when the same author has more than one work in the same year.' },
    ],
    faq: [
      { q: 'Is ASA an author-year style?', a: 'Yes. ASA cites in the text with author last name and year, and lists full references alphabetically, similar to other social science styles.' },
      { q: 'How does ASA mark a page in an in-text citation?', a: 'ASA uses a colon between the year and the page, for example (Smith 2024:48), rather than a comma.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'book',
    answer: 'In ASA cite a book in the text with author and year, and in the reference list give author, year, the title in italics, the place, and the publisher. ASA uses author-year conventions for sociology writing.',
    steps: [
      { name: 'Author and year', text: 'Invert the author name and follow it with the year, as ASA places the date after the author.' },
      { name: 'Italicize the title', text: 'Set the full book title in italics.' },
      { name: 'Place and publisher', text: 'Give the place of publication and the publisher.' },
      { name: 'Edition', text: 'Add the edition after the title when it is not the first.' },
      { name: 'In-text page', text: 'In the text, add a page after a colon for a direct quotation.' },
    ],
    formatNote: 'ASA orders a book as author, year, title, place, and publisher. The worked example shows the reference entry and the in-text form with its colon page style.',
    variations: [
      { q: 'How do I cite a chapter in an edited book in ASA?', a: 'Give the chapter author, year, and chapter title, then Pp. with the page range in the edited book title, the editor, the place, and the publisher.' },
      { q: 'How do I cite a book with an organization as author in ASA?', a: 'Use the organization as the author in both the text and the reference list, common for institutional and government books.' },
      { q: 'How do I cite a later edition of a book in ASA?', a: 'Add the edition after the title and use the year of that edition as the date in the citation.' },
      { q: 'How do I cite a reprinted classic in ASA?', a: 'Cite the edition you used with its year, and you may add the original publication year where it matters to your argument.' },
    ],
    faq: [
      { q: 'Does ASA put the year next to the author for a book?', a: 'Yes. As an author-year style, ASA places the year immediately after the author in the reference list.' },
      { q: 'Is the book title italicized in ASA?', a: 'Yes. The full book title is italicized in the reference list.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'website',
    answer: 'In ASA cite a web page with author or organization, year, the page title, the website name, the access date, and the URL. The in-text citation uses author and year, with the access date written as Retrieved before the URL.',
    steps: [
      { name: 'Author or owner', text: 'Use the page author, or the organization that owns the content when no individual is named.' },
      { name: 'Year', text: 'Give the publication or revision year after the author.' },
      { name: 'Title and site', text: 'Provide the page title and the website name.' },
      { name: 'Retrieval', text: 'Add the access date introduced by Retrieved, which ASA uses for web content.' },
      { name: 'URL', text: 'Paste the full URL to the exact page after the retrieval date.' },
    ],
    formatNote: 'ASA orders a web page as author, year, page title, site, and a Retrieved access date with the URL. The worked example shows the retrieval phrasing ASA uses.',
    variations: [
      { q: 'How do I cite a website with no author in ASA?', a: 'Use the organization that owns the site as the author. If none is identifiable, begin with the page title and use a short form of it in the text.' },
      { q: 'How do I cite a website with no date in ASA?', a: 'Use N.d. in place of the year, and rely on the Retrieved access date as the time anchor for the page.' },
      { q: 'Does ASA require a retrieval date for websites?', a: 'ASA includes a Retrieved access date for web sources, since online content can change after you cite it.' },
      { q: 'How do I cite a blog post in ASA?', a: 'Give the post author, year, post title, the blog name, and the Retrieved access date with the URL, treating it like a web page.' },
    ],
    faq: [
      { q: 'How does ASA write the access date for a website?', a: 'ASA introduces the access date with the word Retrieved, followed by the date and the URL.' },
      { q: 'Is the page title italicized for a website in ASA?', a: 'The website name is italicized while the page title is set in roman or quotation marks, depending on how the source is framed.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'youtube',
    answer: 'In ASA cite a YouTube video with the uploader, the year, the video title, YouTube, and the URL with a Retrieved access date, treating it as an online audiovisual source. Note a timestamp in the text for a specific moment.',
    steps: [
      { name: 'Uploader', text: 'Use the channel or account that posted the video as the author.' },
      { name: 'Year', text: 'Give the upload year after the uploader.' },
      { name: 'Title the video', text: 'Provide the video title as shown on the watch page.' },
      { name: 'Platform and retrieval', text: 'Name YouTube and add a Retrieved access date with the watch URL.' },
      { name: 'Timestamp', text: 'In the text, add the timestamp for the exact moment you reference.' },
    ],
    formatNote: 'ASA orders a YouTube video as uploader, year, title, YouTube, and a Retrieved access date with the URL. A timestamp in the text pinpoints the moment, which the worked example shows.',
    variations: [
      { q: 'How do I cite a specific moment in a YouTube video in ASA?', a: 'Give the uploader and year in the text and add the timestamp, for example (TED 2010), at 4:35, since a video has no pages.' },
      { q: 'How do I cite a research or lecture video on YouTube in ASA?', a: 'Use the channel as the author, the upload year, the video title, YouTube, and the Retrieved access date with the URL.' },
      { q: 'How do I cite a YouTube video with no upload date in ASA?', a: 'Use N.d. for the year and rely on the Retrieved access date, since streaming content can be edited or removed.' },
      { q: 'Is the uploader or speaker the author of a YouTube video in ASA?', a: 'The uploader is the author because they control the posted version, though you can name the speaker in your sentence.' },
    ],
    faq: [
      { q: 'Does ASA use a retrieval date for YouTube videos?', a: 'Yes. As an online source, a YouTube video takes a Retrieved access date alongside the URL.' },
      { q: 'How do I pinpoint a moment in a YouTube video in ASA?', a: 'Use a timestamp such as at 4:35 in the text, since there are no page numbers to cite.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'image',
    answer: 'In ASA cite an image with the creator, the year, a title or description, the medium, and the repository or website with a Retrieved access date and URL. The in-text citation uses the creator and year, or the title when no creator is named.',
    steps: [
      { name: 'Creator', text: 'Give the artist or photographer as the author; if unknown, begin with the title or a description.' },
      { name: 'Year', text: 'Provide the year the image was created or published.' },
      { name: 'Title or describe', text: 'Use the formal title or a short description for an untitled work.' },
      { name: 'Medium and repository', text: 'Note the medium and name the archive, museum, or website holding the image.' },
      { name: 'Retrieval and URL', text: 'For an online image, add a Retrieved access date with the full URL.' },
    ],
    formatNote: 'ASA orders an image as creator, year, title or description, medium, and repository, with a Retrieved access date for online items. The worked example shows the online image form.',
    variations: [
      { q: 'How do I cite an image with no creator in ASA?', a: 'Begin with the title or a description and use it as the in-text anchor, then give the year, the repository, and the Retrieved URL.' },
      { q: 'How do I cite a chart or infographic in ASA?', a: 'Name the producing organization as the creator, the year, the title, the source, and the Retrieved access date with the URL.' },
      { q: 'How do I cite a figure reproduced from another study in ASA?', a: 'Cite the source the figure came from and add a credit line under the figure, with the full entry in the reference list.' },
      { q: 'How do I cite a historical photograph from an archive in ASA?', a: 'Give the photographer if named or a description if not, the year, the holding archive, and the Retrieved URL or collection identifier.' },
    ],
    faq: [
      { q: 'Does an image need a creator in ASA?', a: 'Not always. When no creator is named, start with the title or a description and use that as the in-text anchor.' },
      { q: 'Does ASA add a retrieval date for online images?', a: 'Yes. An online image takes a Retrieved access date along with the URL.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'pdf',
    answer: 'In ASA cite a PDF by the underlying work, usually a report or document, giving author or issuing body, year, the title in italics, the publisher, and a Retrieved access date with the URL. ASA does not treat PDF as its own source type.',
    steps: [
      { name: 'Identify the work', text: 'Decide whether the PDF is a report, book, or article, since that sets the ASA pattern, not the file format.' },
      { name: 'Author or issuer', text: 'Use the named author or the organization that issued the document.' },
      { name: 'Year and title', text: 'Give the year after the author and italicize a standalone report title.' },
      { name: 'Publisher', text: 'Name the issuing body or publisher.' },
      { name: 'Retrieval and URL', text: 'Add a Retrieved access date with the full URL to the PDF.' },
    ],
    formatNote: 'ASA treats a PDF report as author, year, title, publisher, and a Retrieved URL. The format label is optional, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a government report PDF in ASA?', a: 'Use the issuing agency as the author, give the year, the report title and any number, the publisher, and the Retrieved access date with the URL.' },
      { q: 'How do I cite a research center working paper PDF in ASA?', a: 'Name the author or center, the year, the paper title and series number, and the Retrieved URL, common in sociology research.' },
      { q: 'Do I write PDF in an ASA citation?', a: 'Usually no. ASA cites the underlying document and uses the URL, adding a format note only when it helps the reader find the file.' },
      { q: 'How do I cite a PDF with no clear author in ASA?', a: 'Use the issuing organization as the author, or begin with the title when none is shown, keeping the author-year order in the text.' },
    ],
    faq: [
      { q: 'Is a PDF a separate source type in ASA?', a: 'No. ASA cites the underlying report, book, or article and treats PDF only as the delivery format.' },
      { q: 'Does ASA add a retrieval date for a PDF?', a: 'For an online PDF, yes; ASA uses a Retrieved access date with the URL to the file.' },
    ],
  },
  {
    styleId: 'asa',
    sourceId: 'chatgpt',
    answer: 'ASA has no fixed AI rule, so cite ChatGPT by adapting its author-year approach. Credit OpenAI, name ChatGPT and the version, give the year, describe the prompt, and note that the conversation is not retrievable, often handling it in the text rather than as a normal reference.',
    steps: [
      { name: 'Credit the owner', text: 'Use OpenAI as the author, since it makes and is responsible for ChatGPT.' },
      { name: 'Name the tool and version', text: 'Identify ChatGPT and the model version, because outputs differ across versions.' },
      { name: 'Describe the prompt', text: 'State in the text what you asked, since the prompt drives the generated response.' },
      { name: 'Date the response', text: 'Give the date you generated the output, as the same prompt can return different answers later.' },
      { name: 'Note non-retrievability', text: 'Add the tool URL and note that your specific session is not publicly retrievable.' },
    ],
    formatNote: 'ASA adapts its author-year approach for ChatGPT, crediting OpenAI with the date and tool URL. Because the output is not retrievable, the worked example reflects that limitation.',
    variations: [
      { q: 'How do I write the in-text citation for ChatGPT in ASA?', a: 'Give OpenAI and the year in parentheses, naming ChatGPT and the prompt in your sentence so the reader knows what produced the text.' },
      { q: 'Does ChatGPT go in the ASA reference list?', a: 'Because the conversation is not retrievable, many writers handle it in the text; add a reference entry only if your instructor requires one.' },
      { q: 'How do I cite a specific ChatGPT model version in ASA?', a: 'Name the version alongside ChatGPT, since the model used shapes the output and shows readers which system answered.' },
      { q: 'Which date do I use for ChatGPT in ASA?', a: 'Use the date you generated the response, because AI output is not stable and the date fixes when it was produced.' },
    ],
    faq: [
      { q: 'Does ASA have an official AI citation rule?', a: 'Not yet. Writers adapt the author-year approach, crediting OpenAI and treating the output as non-retrievable.' },
      { q: 'Who is the author of a ChatGPT response in ASA?', a: 'OpenAI is credited as the author, with ChatGPT and its version named as the tool that generated the text.' },
    ],
  },
];
