export default [
  {
    styleId: 'bluebook',
    sourceId: 'journal-article',
    answer: 'In Bluebook a journal article is a law review style citation: author, the article title in italics, the volume, the abbreviated journal name, the first page and any pinpoint page, and the year in parentheses. Non-legal articles follow the same author, title, volume, journal, page, year order.',
    steps: [
      { name: 'Author', text: 'Give the author full name as printed, in normal order, since Bluebook does not invert author names.' },
      { name: 'Italicize the title', text: 'Set the article title in italics, capitalized in the journal style.' },
      { name: 'Volume and journal', text: 'Put the volume number before the abbreviated journal name, using Bluebook table abbreviations.' },
      { name: 'Page and pinpoint', text: 'Give the first page of the article, then the pinpoint page you are relying on after a comma.' },
      { name: 'Year', text: 'Close with the year of publication in parentheses.' },
    ],
    formatNote: 'Bluebook orders a law review article as author, italicized title, volume, abbreviated journal, first page with pinpoint, and year in parentheses. The worked example shows the abbreviation and pinpoint placement.',
    variations: [
      { q: 'How do I pinpoint a specific page in a Bluebook article citation?', a: 'After the first page of the article, add a comma and the exact page you cite, so 100, 112 means the article starts at 100 and you rely on page 112.' },
      { q: 'How do I abbreviate the journal name in Bluebook?', a: 'Use the abbreviations in the Bluebook tables for periodicals and institutions, since the journal name is almost always shortened rather than spelled out.' },
      { q: 'How do I cite a student-written note in a law review in Bluebook?', a: 'Begin with the designation such as Note or Comment in place of an author when the piece is unsigned, then give the title, volume, journal, page, and year.' },
      { q: 'How do I cite a journal article with a DOI or URL in Bluebook?', a: 'Bluebook prefers the print citation. Add a URL only when the source is online-only or hard to find in print, appended after the citation.' },
    ],
    faq: [
      { q: 'Does Bluebook invert the author name for an article?', a: 'No. Bluebook gives the author name in ordinary order, unlike Chicago or APA, which invert the surname.' },
      { q: 'Is the article title italicized in Bluebook?', a: 'Yes. In law review style the article title is italicized and the journal name is abbreviated in roman.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'book',
    answer: 'In Bluebook a book is cited with the author in ordinary order, the title in large and small capitals or italics depending on context, the pinpoint page, and the year in parentheses, with the edition noted where it is not the first.',
    steps: [
      { name: 'Author', text: 'Give the author name in normal order; Bluebook uses small capitals for authors in many book citations.' },
      { name: 'Title', text: 'Cite the book title, set in large and small capitals in law review style.' },
      { name: 'Pinpoint page', text: 'Give the exact page or section you rely on rather than the whole book.' },
      { name: 'Edition', text: 'Add the edition if it is not the first, since Bluebook tracks the version you consulted.' },
      { name: 'Year', text: 'Close with the year of publication in parentheses, with the publisher only where required.' },
    ],
    formatNote: 'Bluebook orders a book as author, title, pinpoint, edition, and year in parentheses. Law review style uses small capitals for the author and title, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a specific section of a treatise in Bluebook?', a: 'Use the section symbol and number as the pinpoint, for example § 12.3, which is common for treatises organized by section rather than page.' },
      { q: 'How do I cite an edited or multi-author book in Bluebook?', a: 'Name the editor with ed. after the title, or list multiple authors separated by ampersand, following the Bluebook rule for two or more authors.' },
      { q: 'How do I cite a later edition of a book in Bluebook?', a: 'Add the edition number and the year of that edition in the parenthetical, since the edition you cite must match the page you pinpoint.' },
      { q: 'How do I cite a book chapter by a different author in Bluebook?', a: 'Give the chapter author and title, then in the book title, the editor, the pinpoint page, and the year in parentheses.' },
    ],
    faq: [
      { q: 'Does Bluebook use small capitals for book titles?', a: 'In law review style, author and book titles are set in large and small capitals; typewritten court documents use ordinary or underlined type instead.' },
      { q: 'Do I include the publisher for a book in Bluebook?', a: 'Bluebook generally gives the year and edition in the parenthetical, adding the publisher only where the rule requires it for the source type.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'website',
    answer: 'In Bluebook an internet source is cited with the author, the page or document title, the website name, the full URL, and a date parenthetical, with last updated or last visited used to fix the time the content existed.',
    steps: [
      { name: 'Author or owner', text: 'Give the author if named, otherwise the organization or owner of the site.' },
      { name: 'Title', text: 'Provide the title of the specific page or document, italicized where Bluebook calls for it.' },
      { name: 'Website name', text: 'Name the site itself, since the page sits within a larger web source.' },
      { name: 'URL', text: 'Give the full and direct URL to the exact page rather than the home page.' },
      { name: 'Date parenthetical', text: 'Add a date parenthetical using last updated, or last visited when no posting date is shown.' },
    ],
    formatNote: 'Bluebook orders an internet source as author, title, site, URL, and a date parenthetical. The choice of last updated versus last visited depends on what the page shows, which the worked example reflects.',
    variations: [
      { q: 'When do I use last visited versus last modified for a website in Bluebook?', a: 'Use the last modified or last updated date when the page shows one. When no posting or update date appears, use last visited with the date you accessed it.' },
      { q: 'How do I cite a website with no author in Bluebook?', a: 'Begin with the owning organization, or with the title if no author or organization is identifiable, then give the site, URL, and date parenthetical.' },
      { q: 'How do I cite a PDF posted on a government website in Bluebook?', a: 'Cite the document by its title and issuing body, then give the direct URL to the file with the appropriate date parenthetical.' },
      { q: 'Do I need to archive a web source in Bluebook?', a: 'Bluebook encourages citing a stable archived URL for sources likely to change or disappear, adding it so the cited content stays retrievable.' },
    ],
    faq: [
      { q: 'Does Bluebook require an access date for websites?', a: 'A date parenthetical is required; you use last updated where the page is dated, and last visited where it is not.' },
      { q: 'Should the URL appear in the Bluebook web citation?', a: 'Yes. The direct URL to the specific page is given so the source can be located.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'youtube',
    answer: 'In Bluebook a YouTube video is cited as an internet audiovisual source with the uploader, the video title in italics, YouTube as the site, the full URL, and a posting date parenthetical, with a timestamp added to point to a precise moment.',
    steps: [
      { name: 'Uploader', text: 'Give the account or channel that posted the video as the author of the online source.' },
      { name: 'Italicize the title', text: 'Set the video title in italics as the title of the specific work.' },
      { name: 'Platform', text: 'Identify YouTube as the website hosting the video.' },
      { name: 'URL', text: 'Provide the full watch URL to the specific video.' },
      { name: 'Date and timestamp', text: 'Add the posting date in the parenthetical, and a timestamp such as at 4:35 to pinpoint the cited moment.' },
    ],
    formatNote: 'Bluebook orders a YouTube video as uploader, italicized title, YouTube, URL, and posting date parenthetical. A timestamp pinpoints the cited moment, which the worked example reflects.',
    variations: [
      { q: 'How do I pinpoint a moment in a YouTube video in Bluebook?', a: 'Add the timestamp after the citation, for example at 4:35, since a video has no pages and the time anchors the exact point you rely on.' },
      { q: 'How do I cite a YouTube video posted by an institution in Bluebook?', a: 'Use the institution channel name as the uploader and author, then the italicized title, YouTube, the URL, and the posting date parenthetical.' },
      { q: 'How do I cite a YouTube video with no posting date in Bluebook?', a: 'Use last visited with your access date in the parenthetical when the upload date is not shown, so the time the content existed is still fixed.' },
      { q: 'Is YouTube a website or audiovisual source in Bluebook?', a: 'It is cited under the internet rules as an online audiovisual source, so it takes a URL and a date parenthetical rather than a recording medium label.' },
    ],
    faq: [
      { q: 'Do I italicize a YouTube video title in Bluebook?', a: 'Yes. The specific video title is italicized, while YouTube as the site name stays in roman.' },
      { q: 'Who is the author of a YouTube video in Bluebook?', a: 'The uploader or channel that posted the video is treated as the author of the online source.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'image',
    answer: 'In Bluebook an image is cited by its creator, a title or description, the source or repository that holds it, and a URL with a date parenthetical when it is online, often introduced as a photo or figure so the reader knows the medium.',
    steps: [
      { name: 'Creator', text: 'Give the photographer or artist as the author if named; otherwise begin with the title or a description.' },
      { name: 'Title or describe', text: 'Provide the image title in italics, or a bracketed description when the work is untitled.' },
      { name: 'Medium signal', text: 'Signal that the source is a photo or figure so the reader understands what is cited.' },
      { name: 'Repository', text: 'Name the archive, museum, or website holding the image as the source.' },
      { name: 'URL and date', text: 'For an online image, give the direct URL and a last visited or posting date parenthetical.' },
    ],
    formatNote: 'Bluebook treats an image as an internet or archival source, citing creator, title or description, repository, URL, and a date parenthetical. The worked example shows the online image form.',
    variations: [
      { q: 'How do I cite a photograph with no named photographer in Bluebook?', a: 'Begin with a description of the image, then name the holding archive or website as the source, and give the URL with a date parenthetical.' },
      { q: 'How do I cite an image hosted on a government website in Bluebook?', a: 'Treat it as an internet source, giving the title or description, the issuing body or site, the direct URL, and the appropriate date parenthetical.' },
      { q: 'How do I cite a figure reproduced from a court filing in Bluebook?', a: 'Cite the underlying document the figure came from using the rule for that document type, then point to the figure or exhibit number as the pinpoint.' },
      { q: 'How do I cite a museum artwork viewed online in Bluebook?', a: 'Give the artist and italicized title, the holding museum, and the direct URL to the work with a last visited date parenthetical.' },
    ],
    faq: [
      { q: 'Does an image always have an author in Bluebook?', a: 'No. When no creator is named, you begin with a title or a bracketed description and rely on the repository as the source.' },
      { q: 'Do I need a URL for an image in Bluebook?', a: 'For an online image, yes, with a date parenthetical; an image seen in person is cited by its repository and location.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'pdf',
    answer: 'In Bluebook a PDF is cited by the underlying document, most often a report, government document, or agency publication, giving the author or issuing body, the title, a pinpoint, the year, and the direct URL to the file with a date parenthetical.',
    steps: [
      { name: 'Identify the document', text: 'Determine the underlying source type, such as a government report or agency document, since that controls the rule, not the file format.' },
      { name: 'Author or issuer', text: 'Give the author or the issuing agency as the responsible body.' },
      { name: 'Title and pinpoint', text: 'Provide the document title and the exact page or section you rely on.' },
      { name: 'Year', text: 'Add the year of the document in the parenthetical.' },
      { name: 'URL and date', text: 'Give the direct URL to the PDF and a date parenthetical for online retrieval.' },
    ],
    formatNote: 'Bluebook cites the document inside the PDF rather than the file itself, giving issuer, title, pinpoint, year, and URL with a date parenthetical. The worked example shows the report form.',
    variations: [
      { q: 'How do I cite a government report PDF in Bluebook?', a: 'Use the issuing agency as the author, give the report title and any number, the pinpoint page, the year, and the direct URL with a date parenthetical.' },
      { q: 'How do I pinpoint inside a PDF in Bluebook?', a: 'Cite the printed page number shown in the document where it exists, since that is more stable than the PDF viewer page count.' },
      { q: 'Does the format PDF appear in a Bluebook citation?', a: 'Not as a label. Bluebook cites the underlying document and uses the direct URL to the file rather than naming the format.' },
      { q: 'How do I cite a PDF of an agency rule or guidance in Bluebook?', a: 'Follow the rule for that document type, naming the agency, the title, the pinpoint, the year, and the URL to the posted PDF.' },
    ],
    faq: [
      { q: 'Is a PDF its own source type in Bluebook?', a: 'No. You cite the report, government document, or other underlying work and treat the PDF only as where you retrieved it.' },
      { q: 'Which page do I cite inside a PDF in Bluebook?', a: 'Use the page number printed on the document, falling back to the PDF page only when the document is unpaginated.' },
    ],
  },
  {
    styleId: 'bluebook',
    sourceId: 'chatgpt',
    answer: 'Bluebook has no fixed rule for AI chatbots, so cite ChatGPT as an internet source by analogy: credit OpenAI, name ChatGPT and its version, give the date, note that the output is not retrievable, and add the tool URL with a last visited parenthetical.',
    steps: [
      { name: 'Credit the owner', text: 'Name OpenAI as the entity responsible for the tool.' },
      { name: 'Identify the tool', text: 'State that the source is ChatGPT and give the model version, since outputs vary by version.' },
      { name: 'Describe the prompt', text: 'Explain in the text or parenthetical what you asked, because the prompt drives the output.' },
      { name: 'Date the response', text: 'Give the date you generated the response, the key time anchor for a non-retrievable source.' },
      { name: 'URL and retrievability', text: 'Add the tool URL with a last visited parenthetical, and note that the specific session cannot be retrieved.' },
    ],
    formatNote: 'Bluebook has no dedicated AI rule, so ChatGPT is cited by analogy to the internet rules, crediting OpenAI with the date and tool URL. The worked example reflects the non-retrievable nature of the output.',
    variations: [
      { q: 'How do I show a ChatGPT response is not retrievable in Bluebook?', a: 'Note in a parenthetical that the specific session is on file with the author or is not publicly retrievable, since the conversation cannot be reached through the tool URL.' },
      { q: 'Which date do I use when citing ChatGPT in Bluebook?', a: 'Use the date you generated the response as the operative date, formatted in the last visited style, because the same prompt can return different output later.' },
      { q: 'How do I credit the prompt when citing ChatGPT in Bluebook?', a: 'Describe the prompt in your text or in a parenthetical so the reader understands what produced the quoted or paraphrased output.' },
      { q: 'Can I cite a shared ChatGPT link in Bluebook?', a: 'If a public share link stays live, you may give it as the URL; otherwise use the tool URL and note that your session is not retrievable.' },
    ],
    faq: [
      { q: 'Does Bluebook have an official rule for AI chatbots?', a: 'No formal rule yet, so practitioners adapt the internet source rules, crediting the owner and treating the output as non-retrievable.' },
      { q: 'Who is the author of a ChatGPT response in Bluebook?', a: 'OpenAI, as the entity behind ChatGPT, is credited, with ChatGPT and its version named as the tool.' },
    ],
  },
];
