export default [
  {
    styleId: 'chicago',
    sourceId: 'journal-article',
    answer: 'Chicago has two systems. In notes-bibliography, cite a journal article in a footnote then a bibliography entry, both built from author, article title, journal, volume, issue, year, page, and DOI. In author-date, give the author and year in parentheses with a matching reference list entry.',
    steps: [
      { name: 'Pick your system', text: 'Decide whether your paper uses Chicago notes-bibliography or author-date, since the article reference is ordered differently in each.' },
      { name: 'Author and title', text: 'List the author last name first in the bibliography, with the article title in quotation marks and the journal name in italics.' },
      { name: 'Volume, issue, year', text: 'Add the volume number, the issue number, and the year, which Chicago places in parentheses after the issue.' },
      { name: 'Page range', text: 'Give the full page range of the article in the bibliography, and the specific page you cite in the note.' },
      { name: 'Add the DOI', text: 'Close with the DOI as a full https doi.org link, which Chicago prefers over a database URL.' },
    ],
    formatNote: 'Chicago orders a journal article as author, article title, journal, volume, issue, year, pages, and DOI. The footnote and bibliography entry differ in punctuation and name order, so the worked example shows both.',
    variations: [
      { q: 'How do I cite a journal article with a DOI in Chicago?', a: 'Place the DOI at the end as a full https doi.org URL. Chicago treats the DOI as the stable locator and you do not need to add an access date when a DOI is present.' },
      { q: 'How do I write the footnote versus the bibliography entry for an article in Chicago?', a: 'The footnote lists the author first name first, separates elements with commas, and ends with the specific page. The bibliography entry inverts the first author name, uses periods, and gives the full page range.' },
      { q: 'How do I cite a journal article with no DOI in Chicago?', a: 'If there is no DOI, give the database name or a stable URL instead. For a print article with neither, end the reference at the page range.' },
      { q: 'How do I shorten repeat citations of an article in Chicago notes?', a: 'After the first full footnote, use a shortened note of author last name, a short title, and the page. Chicago no longer recommends ibid for most papers.' },
    ],
    faq: [
      { q: 'Does Chicago author-date use footnotes for articles?', a: 'No. Author-date puts an author and year parenthetical in the text and lists the full article in a reference list, so footnotes are reserved for substantive comments.' },
      { q: 'Should the journal title be italicized in Chicago?', a: 'Yes. The journal name is italicized and the article title is in quotation marks in both Chicago systems.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'book',
    answer: 'Cite a book in Chicago with author, title in italics, place, publisher, and year. Notes-bibliography uses a footnote plus a bibliography entry, while author-date uses an in-text author and year parenthetical with a matching reference entry.',
    steps: [
      { name: 'Pick your system', text: 'Confirm whether you are using notes-bibliography or author-date, since the year sits in a different place in each.' },
      { name: 'Author', text: 'Give the author, inverted in the bibliography and reference list, in normal order in a footnote.' },
      { name: 'Title', text: 'Italicize the full book title, capitalizing it headline style.' },
      { name: 'Publication facts', text: 'Add the place of publication, the publisher, and the year as the imprint details.' },
      { name: 'Locate the page', text: 'In a footnote, end with the specific page you are citing rather than the whole book.' },
    ],
    formatNote: 'Chicago orders a book as author, title, place, publisher, and year. Author-date moves the year next to the author, so the worked example shows both arrangements.',
    variations: [
      { q: 'How do I cite an edited book or a chapter in Chicago?', a: 'For a whole edited book, add edited by and the editor names after the title. For a single chapter, cite the chapter author and title first, then In the book title, the editor, and the page range.' },
      { q: 'How do I cite a specific edition of a book in Chicago?', a: 'Add the edition after the title, such as 3rd ed., before the place and publisher. Use the edition you actually consulted, not the first edition.' },
      { q: 'How do I cite an ebook in Chicago?', a: 'Cite it like a print book and add the format or platform at the end, such as Kindle. If the ebook has no fixed pages, cite by chapter or section in the note.' },
      { q: 'How do I shorten repeat book citations in Chicago notes?', a: 'After the first full note, give the author last name, a short form of the title, and the page. Avoid op cit, which Chicago does not use.' },
    ],
    faq: [
      { q: 'Do I need the place of publication in Chicago?', a: 'Chicago includes the publisher and year for every book and the city where the style or your instructor requires it; recent editions allow dropping the city for well known publishers.' },
      { q: 'Is the book title italicized in Chicago?', a: 'Yes. The full book title and subtitle are italicized in both Chicago systems.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'website',
    answer: 'Cite a web page in Chicago with author or organization, page title in quotation marks, site name, publication or revision date, and URL. Notes-bibliography uses a footnote and a bibliography entry; author-date uses an author and year parenthetical.',
    steps: [
      { name: 'Pick your system', text: 'Decide between notes-bibliography and author-date, since author-date needs a year while a note can use a full date.' },
      { name: 'Author or owner', text: 'Use the page author if named, otherwise the organization or site that owns the content.' },
      { name: 'Title and site', text: 'Put the page title in quotation marks and give the website name separately.' },
      { name: 'Date the page', text: 'Use the publication or last revised date; if none exists, give your access date in the note.' },
      { name: 'Add the URL', text: 'Paste the full URL so the exact page can be reached.' },
    ],
    formatNote: 'Chicago orders a web page as author, page title, site name, date, and URL. When no date is shown, Chicago lets you add an accessed date, so the worked example reflects that.',
    variations: [
      { q: 'How do I cite a website with no author in Chicago?', a: 'Start with the organization that owns the site as the author. If no organization is identifiable, begin with the page title and keep the rest of the order the same.' },
      { q: 'How do I cite a website with no date in Chicago?', a: 'Use n.d. in place of the year and add an access date before the URL, since the access date becomes the only time anchor.' },
      { q: 'Do I need an access date for a website in Chicago?', a: 'Chicago requires an access date only when the page shows no publication or revision date, or when your discipline or instructor asks for one.' },
      { q: 'How do I cite a whole website rather than one page in Chicago?', a: 'You can often describe the site in the text and give the URL in a note rather than a formal bibliography entry. Add a formal entry only if you cite specific content.' },
    ],
    faq: [
      { q: 'Should a website appear in the bibliography in Chicago?', a: 'Frequently cited sites belong in the bibliography. A site mentioned once can sometimes be handled in a note alone, depending on your instructor.' },
      { q: 'Is the page title italicized for a website in Chicago?', a: 'No. The page title goes in quotation marks and the website name is set in roman without italics.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'youtube',
    answer: 'Cite a YouTube video in Chicago by the person or channel that uploaded it, the video title in quotation marks, the word YouTube, the upload date, and the URL. Add the running time or a timestamp in a note when you cite a specific moment.',
    steps: [
      { name: 'Identify the uploader', text: 'Use the channel or account that posted the video as the author, since Chicago treats the uploader as responsible for the content.' },
      { name: 'Title the video', text: 'Put the video title in quotation marks exactly as shown on the watch page.' },
      { name: 'Name the platform', text: 'Add YouTube as the site and note the medium, such as video, where helpful.' },
      { name: 'Upload date', text: 'Give the date the video was posted, not the date you watched it.' },
      { name: 'URL and timestamp', text: 'Paste the full watch URL, and in a note add the timestamp for the exact moment you reference.' },
    ],
    formatNote: 'Chicago orders a YouTube video as uploader, title, YouTube, upload date, and URL. A footnote can add a timestamp to point to a precise moment, which the worked example shows.',
    variations: [
      { q: 'How do I cite a YouTube video where the uploader is a channel name not a person in Chicago?', a: 'Use the channel name as the author exactly as it appears. If a real creator is also credited on the page, you may give the person and note the channel.' },
      { q: 'How do I cite a specific timestamp in a YouTube video in Chicago?', a: 'Add the time in the footnote after the title, for example at 4:35, so the reader can jump to the exact passage you discuss.' },
      { q: 'How do I cite a YouTube video with no upload date in Chicago?', a: 'Use n.d. for the date and add your access date in the note, since streaming content can change or be removed.' },
      { q: 'Should I include the running time of a YouTube video in Chicago?', a: 'You can give the total running time after the medium to signal length, but the timestamp in the note is what locates your specific reference.' },
    ],
    faq: [
      { q: 'Is the uploader or the speaker the author in Chicago?', a: 'Chicago uses the uploader as the author because they control the posted version, though you can name the speaker in your sentence for clarity.' },
      { q: 'Do I italicize a YouTube video title in Chicago?', a: 'No. A short online video title goes in quotation marks rather than italics.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'image',
    answer: 'Cite an image in Chicago with the creator, the title or a description in italics or quotation marks depending on type, the year, the medium, and the repository or website with URL. A caption can carry a short credit while the full entry sits in a note or bibliography.',
    steps: [
      { name: 'Name the creator', text: 'Give the artist or photographer as the author; if unknown, begin with the image title or description.' },
      { name: 'Title or describe', text: 'Use the formal title in italics for artworks, or a brief description in roman when the work has no title.' },
      { name: 'Date and medium', text: 'Add the year created and the medium, such as photograph, painting, or digital image.' },
      { name: 'Repository', text: 'Name the museum, archive, or website that holds the image, with its location where relevant.' },
      { name: 'Add the URL', text: 'For an online image, paste the full URL or stable catalog link to the exact item.' },
    ],
    formatNote: 'Chicago orders an image as creator, title or description, date, medium, and repository or site. Captions and figure references can be shortened, so the worked example shows the full reference form.',
    variations: [
      { q: 'How do I cite an image with no creator in Chicago?', a: 'Begin with the image title or a short description, then the date and the repository. Many archival photographs are cited by collection rather than by a named photographer.' },
      { q: 'How do I cite a figure or chart reproduced from another source in Chicago?', a: 'Cite the source the figure came from and add a credit line under the figure, such as Source, with the full reference in your notes or bibliography.' },
      { q: 'How do I cite a museum artwork I viewed online in Chicago?', a: 'Give the artist, title, date, and medium, then the holding institution, and finish with the museum website URL for the work.' },
      { q: 'How do I cite a stock or web image with only a filename in Chicago?', a: 'Use a brief description in place of a title, name the website or stock service as the source, and give the URL to the specific image page.' },
    ],
    faq: [
      { q: 'Do artwork titles get italicized in Chicago?', a: 'Yes. Titles of paintings, photographs, and other formal artworks are italicized, while an untitled work uses a roman description.' },
      { q: 'Does an image always need a bibliography entry in Chicago?', a: 'A figure with a caption credit may not need a separate entry, but a discussed or analyzed image normally gets a full note or bibliography reference.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'pdf',
    answer: 'Cite a PDF in Chicago by what it is rather than its format. Treat a report, white paper, or government document by its author or issuing organization, title, publisher, year, and URL, adding PDF as the medium only when it helps the reader.',
    steps: [
      { name: 'Identify the work', text: 'Decide whether the PDF is a report, book, article, or government document, since that controls the Chicago pattern, not the file type.' },
      { name: 'Author or issuer', text: 'Use the named author, or the organization that issued the document as a corporate author.' },
      { name: 'Title', text: 'Italicize the title for a standalone report; use quotation marks for a document that is part of a series.' },
      { name: 'Publisher and year', text: 'Give the issuing body or publisher and the publication year.' },
      { name: 'Link the file', text: 'Add the full URL to the PDF, and note PDF as the format where the file type matters.' },
    ],
    formatNote: 'Chicago treats a PDF report as author, title, publisher, year, and URL. The format label PDF is optional and used only when it aids retrieval, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a government report PDF in Chicago?', a: 'Use the issuing agency as the author, give the report title and any report number, then the publishing body, year, and the URL to the PDF.' },
      { q: 'Do I need to write PDF in a Chicago citation?', a: 'Only when the format helps the reader find the file. If the document is clearly a report at a stable URL, the format label can be omitted.' },
      { q: 'How do I cite a PDF that is a scanned chapter or article in Chicago?', a: 'Cite it as the underlying article or chapter with full publication details. The fact it reached you as a PDF does not change the Chicago pattern.' },
      { q: 'How do I cite a PDF with no clear author in Chicago?', a: 'Use the issuing organization as a corporate author. If none is shown, begin with the document title and keep the rest of the order intact.' },
    ],
    faq: [
      { q: 'Is a PDF a separate source type in Chicago?', a: 'No. Chicago cites the underlying work, so you choose the report, book, or article pattern and treat PDF only as a delivery format.' },
      { q: 'Should a report PDF title be italicized in Chicago?', a: 'A standalone report title is italicized; a document that forms part of a larger series uses quotation marks instead.' },
    ],
  },
  {
    styleId: 'chicago',
    sourceId: 'chatgpt',
    answer: 'Chicago treats ChatGPT as a non-retrievable personal-style communication. Credit OpenAI as the author of the tool, name ChatGPT and its version, give the date of the response, and note that the output cannot be linked, usually citing it in a note rather than the bibliography.',
    steps: [
      { name: 'Credit the owner', text: 'Use OpenAI as the author since it is the organization responsible for ChatGPT.' },
      { name: 'Name the tool and version', text: 'Identify ChatGPT and the model version you used, since outputs differ across versions.' },
      { name: 'Describe the prompt', text: 'Note the nature of your prompt in the text or note so readers understand what produced the response.' },
      { name: 'Date the response', text: 'Give the date you generated the response, because the same prompt can return different answers later.' },
      { name: 'Note non-retrievability', text: 'State that the conversation is not publicly retrievable, and add the tool URL rather than a link to your chat.' },
    ],
    formatNote: 'Chicago handles ChatGPT in a note because the output is not recoverable by readers. Credit goes to OpenAI as author with ChatGPT and a date, so the worked example shows the note form.',
    variations: [
      { q: 'Does ChatGPT go in the Chicago bibliography?', a: 'Usually no. Because the conversation cannot be retrieved, Chicago recommends citing it in a footnote, and you add a bibliography entry only if your instructor requires one.' },
      { q: 'How do I credit the prompt when citing ChatGPT in Chicago?', a: 'Mention the prompt in your sentence or in the note, for example noting that you asked ChatGPT to summarize a policy, so the context of the generated text is clear.' },
      { q: 'How do I cite a specific ChatGPT model version in Chicago?', a: 'Name the version alongside ChatGPT, since the model used affects the output and lets readers understand which system produced it.' },
      { q: 'Can I link to my ChatGPT conversation in Chicago?', a: 'If you used a share link that stays live, you may add it, but otherwise give the tool URL and state that your specific session is not retrievable.' },
    ],
    faq: [
      { q: 'Who is the author of a ChatGPT response in Chicago?', a: 'OpenAI, the company that makes ChatGPT, is treated as the author, while ChatGPT is named as the tool that generated the text.' },
      { q: 'Why is ChatGPT cited in a note rather than the reference list in Chicago?', a: 'Because the output is not publicly retrievable, Chicago treats it like personal communication, which is best handled in a note.' },
    ],
  },
];
