export default [
  {
    styleId: 'harvard',
    sourceId: 'journal-article',
    answer: 'Harvard is an author-date referencing system. Cite a journal article in the text with author surname and year, and in the reference list give author, year, the article title in single quotation marks, the journal in italics, volume, issue, and the page range, adding the DOI or URL.',
    steps: [
      { name: 'Author and year', text: 'Invert the surname and place the year right after the author, since Harvard is author-date.' },
      { name: 'Article title', text: 'Give the article title in single quotation marks, in sentence case.' },
      { name: 'Journal and volume', text: 'Italicize the journal name and add the volume and issue numbers.' },
      { name: 'Page range', text: 'Provide the page range, often introduced by pp. in many Harvard variants.' },
      { name: 'DOI or URL', text: 'Close with the DOI or a stable URL so readers can find the article.' },
    ],
    formatNote: 'Harvard orders a journal article as author, year, article title, journal, volume, issue, and pages. Punctuation differs slightly between Harvard guides, so the worked example shows one consistent pattern.',
    variations: [
      { q: 'How do I write the in-text citation for an article in Harvard?', a: 'Give the author surname and year in parentheses, adding a page for a direct quote, for example (Smith, 2024, p. 48).' },
      { q: 'How do I cite an article with three or more authors in Harvard?', a: 'List all authors in the reference list, and in the text use the first author followed by et al. once the author count passes the Harvard threshold.' },
      { q: 'How do I cite a journal article with no DOI in Harvard?', a: 'Give a stable URL and an access date in place of the DOI, or end at the page range for a print article that has neither.' },
      { q: 'Why do Harvard article references differ between universities?', a: 'Harvard is a referencing convention rather than a single manual, so punctuation and the use of pp. vary by institution; follow your own guide consistently.' },
    ],
    faq: [
      { q: 'Is Harvard a single official style?', a: 'No. Harvard is a family of author-date conventions, so small differences in punctuation exist between university guides. Pick one guide and apply it consistently.' },
      { q: 'Is the journal title italicized in Harvard?', a: 'Yes. The journal name is italicized and the article title appears in single quotation marks.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'book',
    answer: 'In Harvard cite a book in the text with author surname and year, and in the reference list give author, year, the title in italics, the edition if not the first, the place, and the publisher. Harvard is an author-date system.',
    steps: [
      { name: 'Author and year', text: 'Invert the surname and follow it with the year, since Harvard places the date after the author.' },
      { name: 'Italicize the title', text: 'Set the full book title in italics, usually in sentence case.' },
      { name: 'Edition', text: 'Add the edition after the title when it is not the first.' },
      { name: 'Place and publisher', text: 'Give the place of publication and the publisher.' },
      { name: 'In-text page', text: 'In the text, add a page for a direct quotation, for example p. 23.' },
    ],
    formatNote: 'Harvard orders a book as author, year, title, edition, place, and publisher. Exact punctuation varies by guide, so the worked example shows one consistent pattern.',
    variations: [
      { q: 'How do I cite a chapter in an edited book in Harvard?', a: 'Give the chapter author, year, and chapter title in single quotes, then in the edited book title, the editor, the place, the publisher, and the page range.' },
      { q: 'How do I cite a book with an organization as author in Harvard?', a: 'Use the organization as the author in both the text and the reference list, common for corporate and government publications.' },
      { q: 'How do I cite an ebook in Harvard?', a: 'Cite it like a print book and add the format or platform and a URL or access date where the version you used has no fixed pages.' },
      { q: 'How do I cite a later edition of a book in Harvard?', a: 'Add the edition after the title and use the year of that edition as the date in the citation.' },
    ],
    faq: [
      { q: 'Does Harvard put the year next to the author for a book?', a: 'Yes. As an author-date system, Harvard places the year immediately after the author in both the text and the reference list.' },
      { q: 'Is the book title italicized in Harvard?', a: 'Yes. The full book title is italicized in the reference list.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'website',
    answer: 'In Harvard cite a web page with author or organization, year, the page title in italics, the website name, the date accessed, and the URL. The in-text citation uses author surname and year, and the access date is given as Accessed before the date.',
    steps: [
      { name: 'Author or owner', text: 'Use the page author, or the organization that owns the content when no individual is named.' },
      { name: 'Year', text: 'Give the publication or revision year after the author.' },
      { name: 'Title and site', text: 'Provide the page title in italics and name the website.' },
      { name: 'Access date', text: 'Add the date accessed, written as Accessed, since web content can change.' },
      { name: 'URL', text: 'Paste the full URL to the exact page, often enclosed in angle brackets in some Harvard guides.' },
    ],
    formatNote: 'Harvard orders a web page as author, year, page title, site, access date, and URL. The Accessed date and bracket style vary by guide, so the worked example shows one consistent pattern.',
    variations: [
      { q: 'How do I cite a website with no author in Harvard?', a: 'Use the organization that owns the site as the author. If none is identifiable, begin with the page title and use a short form of it in the text.' },
      { q: 'How do I cite a website with no date in Harvard?', a: 'Use n.d. in place of the year in both the text and the reference list, and rely on the Accessed date as the time anchor.' },
      { q: 'Does Harvard require an access date for websites?', a: 'Yes. Harvard includes the date you accessed the page, since online content can be updated or removed after you cite it.' },
      { q: 'How do I cite a blog post in Harvard?', a: 'Give the post author, year, post title, the blog name, the access date, and the URL, treating it like a web page.' },
    ],
    faq: [
      { q: 'How does Harvard write the access date for a website?', a: 'Harvard gives the date you viewed the page, usually introduced by Accessed, before or alongside the URL.' },
      { q: 'Is the page title italicized for a website in Harvard?', a: 'Many Harvard guides italicize the web page title; check your own guide, since conventions vary slightly between institutions.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'youtube',
    answer: 'In Harvard cite a YouTube video with the uploader, the year, the video title in italics, the description online video, YouTube, the access date, and the URL. The in-text citation uses uploader and year, with a timestamp for a specific moment.',
    steps: [
      { name: 'Uploader', text: 'Use the channel or account that posted the video as the author.' },
      { name: 'Year', text: 'Give the upload year after the uploader.' },
      { name: 'Title and medium', text: 'Provide the video title in italics and note that it is an online video.' },
      { name: 'Platform and access', text: 'Name YouTube and add the date accessed.' },
      { name: 'URL and timestamp', text: 'Paste the full watch URL, and add a timestamp in the text for the exact moment.' },
    ],
    formatNote: 'Harvard orders a YouTube video as uploader, year, title, medium, YouTube, access date, and URL. A timestamp in the text pinpoints the moment, which the worked example shows.',
    variations: [
      { q: 'How do I cite a specific moment in a YouTube video in Harvard?', a: 'Give the uploader and year in the text and add the timestamp, for example (TED, 2010, at 4:35), since a video has no page numbers.' },
      { q: 'How do I cite an institutional YouTube video in Harvard?', a: 'Use the institution channel as the uploader and author, the upload year, the title, online video, YouTube, the access date, and the URL.' },
      { q: 'How do I cite a YouTube video with no upload date in Harvard?', a: 'Use n.d. for the year and rely on the access date, since streaming content can be edited or removed.' },
      { q: 'Is the uploader or speaker the author of a YouTube video in Harvard?', a: 'The uploader is the author because they control the posted version, though you can name the speaker in your sentence for clarity.' },
    ],
    faq: [
      { q: 'Does Harvard add an access date for YouTube videos?', a: 'Yes. As an online source, a YouTube video takes the date you accessed it alongside the URL.' },
      { q: 'Do I italicize a YouTube video title in Harvard?', a: 'Many Harvard guides italicize the video title and add the medium online video; check your own guide for the exact convention.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'image',
    answer: 'In Harvard cite an image with the creator, the year, the title in italics, the medium such as photograph or illustration, the repository or website, the access date, and the URL. The in-text citation uses creator and year, or the title when no creator is named.',
    steps: [
      { name: 'Creator', text: 'Give the artist or photographer as the author; if unknown, begin with the title or a description.' },
      { name: 'Year', text: 'Provide the year the image was created or published.' },
      { name: 'Title and medium', text: 'Give the title in italics and note the medium, such as photograph or illustration.' },
      { name: 'Repository', text: 'Name the archive, museum, or website holding the image.' },
      { name: 'Access date and URL', text: 'For an online image, add the access date and the full URL.' },
    ],
    formatNote: 'Harvard orders an image as creator, year, title, medium, repository, access date, and URL. The worked example shows the online image form used by most Harvard guides.',
    variations: [
      { q: 'How do I cite an image with no creator in Harvard?', a: 'Begin with the title or a description and use it as the in-text anchor, then give the year, the medium, the repository, the access date, and the URL.' },
      { q: 'How do I cite a diagram or chart in Harvard?', a: 'Name the creator or producing organization, the year, the title, the medium such as diagram, the source, the access date, and the URL.' },
      { q: 'How do I cite a figure reproduced from another source in Harvard?', a: 'Cite the source the figure came from and add a credit line under the figure, with the full entry in the reference list.' },
      { q: 'How do I cite a museum artwork viewed in person in Harvard?', a: 'Give the artist, year, title, the medium, and the holding institution with its location, omitting the URL and access date for an in-person view.' },
    ],
    faq: [
      { q: 'Does an image need a creator in Harvard?', a: 'Not always. When no creator is named, begin with the title or a description and use that as the in-text anchor.' },
      { q: 'Are image titles italicized in Harvard?', a: 'Most Harvard guides italicize the image title and add the medium; check your own guide for the exact convention.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'pdf',
    answer: 'In Harvard cite a PDF by the underlying work, usually a report, giving author or issuing body, year, the title in italics, the type and number if any, the publisher, the access date, and the URL. Harvard does not treat PDF as its own source type.',
    steps: [
      { name: 'Identify the work', text: 'Decide whether the PDF is a report, book, or article, since that sets the Harvard pattern, not the file format.' },
      { name: 'Author or issuer', text: 'Use the named author or the organization that issued the document.' },
      { name: 'Year and title', text: 'Give the year after the author and italicize a standalone report title.' },
      { name: 'Publisher', text: 'Name the issuing body or publisher, and any report type and number.' },
      { name: 'Access date and URL', text: 'Add the date accessed and the full URL to the PDF.' },
    ],
    formatNote: 'Harvard treats a PDF report as author, year, title, publisher, access date, and URL. The format label is optional, which the worked example reflects.',
    variations: [
      { q: 'How do I cite a government report PDF in Harvard?', a: 'Use the issuing agency as the author, give the year, the report title and number, the publisher, the access date, and the URL to the file.' },
      { q: 'How do I cite a research report PDF in Harvard?', a: 'Name the author or organization, the year, the report title, the series and number, the access date, and the URL.' },
      { q: 'Do I write PDF in a Harvard citation?', a: 'Usually no. Harvard cites the underlying document and uses the URL, adding a format note only when it helps the reader find the file.' },
      { q: 'How do I cite a PDF with no clear author in Harvard?', a: 'Use the issuing organization as the author, or begin with the title when none is shown, keeping author-date order in the text.' },
    ],
    faq: [
      { q: 'Is a PDF a separate source type in Harvard?', a: 'No. Harvard cites the underlying report, book, or article and treats PDF only as the delivery format.' },
      { q: 'Does Harvard add an access date for a PDF?', a: 'For an online PDF, yes; Harvard gives the date you accessed it along with the URL to the file.' },
    ],
  },
  {
    styleId: 'harvard',
    sourceId: 'chatgpt',
    answer: 'Harvard has no single AI rule, so cite ChatGPT by adapting its author-date conventions. Credit OpenAI, name ChatGPT and the version, give the year, describe the prompt, add the access date and tool URL, and note that the conversation is not retrievable.',
    steps: [
      { name: 'Credit the owner', text: 'Use OpenAI as the author, since it makes and is responsible for ChatGPT.' },
      { name: 'Name the tool and version', text: 'Identify ChatGPT and the model version, because outputs differ across versions.' },
      { name: 'Describe the prompt', text: 'State in the text what you asked, since the prompt drives the generated response.' },
      { name: 'Date the response', text: 'Give the date you generated the output, as the same prompt can return different answers later.' },
      { name: 'Access, URL and retrievability', text: 'Add the access date and tool URL, and note that your specific session is not publicly retrievable.' },
    ],
    formatNote: 'Harvard adapts its author-date conventions for ChatGPT, crediting OpenAI with the date, access date, and tool URL. Because the output is not retrievable, the worked example reflects that limitation.',
    variations: [
      { q: 'How do I write the in-text citation for ChatGPT in Harvard?', a: 'Give OpenAI and the year in parentheses, naming ChatGPT and the prompt in your sentence so the reader knows what produced the text.' },
      { q: 'Does ChatGPT go in the Harvard reference list?', a: 'Because the conversation is not retrievable, many guides recommend describing it in the text; add a reference entry only if your guide or instructor requires one.' },
      { q: 'How do I cite a specific ChatGPT model version in Harvard?', a: 'Name the version alongside ChatGPT, since the model used shapes the output and shows readers which system answered.' },
      { q: 'Which date do I use for ChatGPT in Harvard?', a: 'Use the date you generated the response together with an access date, because AI output is not stable and these dates fix when it was produced.' },
    ],
    faq: [
      { q: 'Does Harvard have an official AI citation rule?', a: 'Not a single one. Because Harvard is a family of guides, follow your own institution adaptation, crediting OpenAI and treating the output as non-retrievable.' },
      { q: 'Who is the author of a ChatGPT response in Harvard?', a: 'OpenAI is credited as the author, with ChatGPT and its version named as the tool that generated the text.' },
    ],
  },
];
